### ISSUE TITLE
randomForestInfJack question

### ISSUE THREAD

**Issue by MNRiverEcologyUnit** [swager/randomForestCI#7]
I would like to supply a standard error and or confidence intervals with predictions from a random forest.  I found your package and have a simple question, does the randomForestInfJack output the standard error or the variance in var.hat column.  Can one then just use the general 2*sqrt(var.hat) to get a confidence interval.  Thank you for your work and help.

Dan

**Comment by swager** [comment]
var.hat is an estimate of variance; you should take its square too to get standard error estimates. Here, using the "calibrate=TRUE" option makes sure the variance estimates are positive.
